# SQL Notebook: Chapter 2 - Single-Table Queries
## 10 Propositions & Solutions (WideWorldImporters Database)
This notebook contains **10 SQL queries** based on **Chapter 2** exercises, adjusted for the `WideWorldImporters` database.

## Proposition 1: Retrieve Orders from June 2015
**Problem:** Return all orders placed in June 2015.

In [ ]:
USE WideWorldImporters;
SELECT OrderID, OrderDate, CustomerID, SalespersonPersonID
FROM Sales.Orders
WHERE YEAR(OrderDate) = 2015 AND MONTH(OrderDate) = 6;

## Proposition 2: Orders Placed on the Last Day of the Month
**Problem:** Retrieve all orders placed on the last day of any month.

In [ ]:
USE WideWorldImporters;
SELECT OrderID, OrderDate, CustomerID, SalespersonPersonID
FROM Sales.Orders
WHERE OrderDate = EOMONTH(OrderDate);

## Proposition 3: Employees with 'e' Appearing Twice in Last Name
**Problem:** Find employees whose last name contains the letter 'e' at least twice.

In [ ]:
USE WideWorldImporters;
SELECT PersonID, FullName
FROM Application.People
WHERE LEN(FullName) - LEN(REPLACE(FullName, 'e', '')) >= 2;

## Proposition 4: Orders with Total Value Greater Than 10,000
**Problem:** Return orders where `Quantity * UnitPrice > 10,000`, sorted by total value.

In [ ]:
USE WideWorldImporters;
SELECT OrderID, SUM(Quantity * UnitPrice) AS TotalValue
FROM Sales.OrderLines
GROUP BY OrderID
HAVING SUM(Quantity * UnitPrice) > 10000
ORDER BY TotalValue DESC;

## Proposition 5: Employees with Lowercase Last Names
**Problem:** Find employees whose last name starts with a lowercase letter.

In [ ]:
USE WideWorldImporters;
SELECT PersonID, FullName
FROM Application.People
WHERE FullName COLLATE Latin1_General_CS_AS LIKE '[a-z]%';

## Proposition 6: Employee Orders Before May 2016
**Problem:** Compare two different grouping methods for counting orders per employee before May 2016.

In [ ]:
-- Query 1: Using WHERE clause
USE WideWorldImporters;
SELECT SalespersonPersonID, COUNT(*) AS NumOrders
FROM Sales.Orders
WHERE OrderDate < '2016-05-01'
GROUP BY SalespersonPersonID;

In [ ]:
-- Query 2: Using HAVING clause
USE WideWorldImporters;
SELECT SalespersonPersonID, COUNT(*) AS NumOrders
FROM Sales.Orders
GROUP BY SalespersonPersonID
HAVING MAX(OrderDate) < '2016-05-01';

## Proposition 7: Top 3 Customers with the Most Orders in 2015
**Problem:** Find the top 3 customers who placed the most orders in 2015.

In [ ]:
USE WideWorldImporters;
SELECT TOP 3 CustomerID, COUNT(OrderID) AS TotalOrders
FROM Sales.Orders
WHERE YEAR(OrderDate) = 2015
GROUP BY CustomerID
ORDER BY TotalOrders DESC;

## Proposition 8: Row Numbering Orders for Each Customer
**Problem:** Assign row numbers to orders for each customer based on order date.

In [ ]:
USE WideWorldImporters;
SELECT CustomerID, OrderDate, OrderID,
       ROW_NUMBER() OVER(PARTITION BY CustomerID ORDER BY OrderDate, OrderID) AS RowNum
FROM Sales.Orders;

## Proposition 9: Determine Employee Gender Based on Courtesy Title
**Problem:** Assign gender based on `PreferredName`.

In [ ]:
USE WideWorldImporters;
SELECT PersonID, PreferredName, FullName,
       CASE
           WHEN PreferredName LIKE 'Ms.%' OR PreferredName LIKE 'Mrs.%' THEN 'Female'
           WHEN PreferredName LIKE 'Mr.%' THEN 'Male'
           ELSE 'Unknown'
       END AS Gender
FROM Application.People;